# Generated by Django 3.0.3 on 2020-02-12 17:42

from django.db import migrations

from currencies.scrappers import CurrencyScrapper


def create_currencies(apps, schema_editor):
    scrapper = CurrencyScrapper()
    scrapper.create_currencies()


def delete_currencies(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_currencies, delete_currencies)
    ]
